
[shell]
polkit_agent = true
settings_show_advanced = true
telemetry_enabled = true

[shell.launcher]
categories = false
compact = true
fetch_exchange_rates = false

[shell.panel]
transparency_mode = "glass"

[brightness]
minimum_brightness = 0.05

[nightlight]
enabled = true
